server:
  port: 8050

spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
  profiles:
    active: dev

logging:
  level:
    web: info
    sql: error

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/eShop
    username: postgres
    password: postgres
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
